### PR TITLE
This will fix plugin on latest Rollup versions.

### PR DESCRIPTION
**Pull request by PaulMaly**
Please, check this issue for more details: https://github.com/haifeng2013/rollup-plugin-bundle-html/issues/31

### CODE REVIEW

**Review by ThomZz — COMMENTED** [review]
To be ompatible with rollup 2.X ? https://github.com/rollup/rollup/pull/3361 needs to stay compatible with rollup 1.X

**Comment by PaulMaly** [comment]
@ThomZz Seems, it's not compatible with Rollup 1.x already, because of using `writeBundle` instead of removed `onwrite`. Please, check breaking changes: https://github.com/rollup/rollup/blob/master/CHANGELOG.md#breaking-changes

**Comment by PaulMaly** [comment]
@ThomZz Oh, I missed, `writeBundle` was added even earlier, but seems its signature was different:

**The signature of the writeBundle plugin hook has been changed to match generateBundle: The bundle object is now passed as second parameter instead of first and the first parameter is the output options (#3361)**

Looks like, we need to have a way to decide which signature should be used.

**Comment by ThomZz** [comment]
fully compatible with rollup 1.x, using it since long. Indeed, with 2.X, signature has changed. Will keep the PR open, i'm open for a clean solution that is compatible in both versions.

**Comment by PaulMaly** [comment]
Seems, the cleanest solution is to create a separate branch for different versions. Maybe move this fix to `next` branch and published with that tag: `npm install rollup-plugin-bundle-html-thomzz@next`. What do you think about it?

Also, I see a few more hacky ways as well.))))

**Pull request closed without merging**
